#[cfg(feature = "all")]
pub mod day_01;
#[cfg(feature = "all")]
pub mod day_04;
#[cfg(feature = "all")]
pub mod day_06;
#[cfg(feature = "all")]
pub mod day_07;
#[cfg(feature = "all")]
pub mod day_08;
#[cfg(feature = "all")]
pub mod day_11;
#[cfg(feature = "all")]
pub mod day_12;
#[cfg(feature = "all")]
pub mod day_13;
#[cfg(feature = "all")]
pub mod day_14;
#[cfg(feature = "all")]
pub mod day_15;
#[cfg(feature = "all")]
pub mod day_18;
#[cfg(feature = "all")]
pub mod day_19;
#[cfg(feature = "all")]
pub mod day_20;
#[cfg(any(feature = "past", feature = "current"))]
pub mod day_21;
